### PR TITLE
XDS Changes related to Connectathon.

### PR DESCRIPTION
**Pull request by davidbuccola**
Hi Martin,

Here are a collection of changes that I made as a result of this year's Connectathon.
- Dave Buccola

### CODE REVIEW

**Comment by unixoid** [comment]
Hi David,
thank you very much for the patches!  Your work is highly appreciated.  I will integrate them in the next week -- along with the ones I collected at the Eurpoean Connectathon this week.
Kind Regards,
Dmytro

**Comment by krasserm** [comment]
Hi David, thanks a lot for your patches! 
@unixoid, thanks for including them!

**Comment by unixoid** [comment]
Merged into IPF-2.2 branch

**Comment by davidbuccola** [comment]
Thanks!

**Pull request merged**
