### PR TITLE
Serialized RetreiveImagingDocumentSet Classes

### PR DESCRIPTION
**Pull request by clayseag**
Hi Dmytro,

This change adds serialization to the RetrieveImagingDocumentSet classes:
- RetrieveImagingDocumentSet
- RetrieveStudy
- RetrieveSeries

Thanks,

Clay

### CODE REVIEW

**Comment by unixoid** [comment]
Hi Clay,

your patches do not seem to base on the latest version of IPF sources.  In particular, it does not seem appropriate to revert the changed serialVersionUID of RetrieveImagingDocumentSet and to make it again the same as in RetrieveDocumentSet, as well as to restore obsolere copyright notices.  Cound you please actualize the patch?

Thanks and Best Regards
Dmytro

**Comment by clayseag** [comment]
I’m sorry Dmytro.  I thought my code was the latest and didn’t realize your pull may have updated it.  I will make these changes ASAP.

**Comment by unixoid** [comment]
Deprecated by #97

**Comment by clayseag** [comment]
Thanks…

**Pull request closed without merging**
