### PR TITLE
XCA-I

### PR DESCRIPTION
**Pull request by clayseag**
This is the pull request for XCA-I implementation.

### CODE REVIEW

**Comment by unixoid** [comment]
Hi Clay,

Thank you for the contribution!  I'm merging it now.  Could you please tell
me where did you get ATNA Audit record definitions for RAD-69 and RAD-75
from?

Best Regards
Dmytro

2012/8/7 Clay Sebourn notifications@github.com

**Comment by clayseag** [comment]
Hi Dmytro,

I couldn’t find any specific details concerning ATNA audit requirements in either the XDS-I.b or XCA-I spec, so I left it the same as it is for RetrieveDocument. Do you know of any more specific requirements?

Thanks,

Clay

**Comment by unixoid** [comment]
Hi Clay,

I couldn't find any specifications too -- that's why I'm asking.  I simply
wanted to understand why do the audit strategies collect study instance IDs
and series instance IDs, while these values are in fact not used in audit
records.  Ok, I'll keep the routines as-is -- in the hope that IHE will
specify audit record structures in the near future...

Best Regards
Dmytro

2012/8/8 Clay Sebourn notifications@github.com

**Comment by clayseag** [comment]
I put/left them in thinking they may be needed, but you can remove them if it seems best to you.  There are also other properties which are not used, but I wanted their signatures to be as close as possible.  Please modify as you like.

Thanks

**Comment by unixoid** [comment]
Ok.

2012/8/8 Clay Sebourn notifications@github.com

**Comment by unixoid** [comment]
Hi Clay,

I committed your code -- thank you for contributing!  The only thing I had to fix is the WS-Addressing action in ITI-69 WSDL and SEI class.  Moreover, I provided an alternative implementation of ATNA auditors.  Please take a look at my today's commit prefixed "After #95".

Best Regards
Dmytro

**Comment by clayseag** [comment]
I see the action was wrong in rad69.wsdl…thanks!

**Pull request merged**
